services:
  traefik:
    image: traefik:v3.3
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
 
  frontend_af:
    build:
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend_af.rule=PathPrefix(`/wordnet-af`)
      - traefik.http.services.frontend_af.loadbalancer.server.port=80
 
  backend_af:
    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_af.rule=PathPrefix(`/api/dict`) && Headers(`X-Lang`, `af`)
      - traefik.http.services.backend_af.loadbalancer.server.port=5000      
 