version: "2"
services:
  frontend_ua:
    build:
      context: ./frontend    
    ports:
      - "8086:8086"
    networks:
      - my-net 
  backend_ua:
    build:
      context: ./backend    
    ports:
      - "5006:5006"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge 
    name: my-net
    external: true