services:
  frontend_de:
    build:
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend_de.rule=PathPrefix(`/wordnet-de`)
      - traefik.http.routers.frontend_de.middlewares=frontend_de-stripprefix
      - traefik.http.services.frontend_de.loadbalancer.server.port=80
      - traefik.http.middlewares.frontend_de-stripprefix.stripprefix.prefixes=/wordnet-de
    networks:
      - lang-network      
 
  backend_de:
    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_de.rule=PathPrefix(`/api/dict`) && Header(`X-Lang`, `de`)
      - traefik.http.services.backend_de.loadbalancer.server.port=5000
    networks:
      - lang-network      

networks:
  lang-network:
    external: true 