version: "2"
services:
  frontend_af:
    build:
      context: ./frontend    
    ports:
      - "8083:80"
    networks:
      - my-net-af  
  backend_af:
    build:
      context: ./backend    
    ports:
      - "5003:5000"
    networks:
      - my-net-af

networks:
  my-net-af:
