services:
  frontend_eu:
    build:
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend_eu.rule=PathPrefix(`/wordnet`)
      - traefik.http.routers.frontend_eu.middlewares=frontend_eu-stripprefix
      - traefik.http.services.frontend_eu.loadbalancer.server.port=80
      - traefik.http.middlewares.frontend_eu-stripprefix.stripprefix.prefixes=/wordnet
    networks:
      - lang-network      
 
  backend_eu:
    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_eu.rule=PathPrefix(`/api/dict`) && Header(`X-Lang`, `eu`)
      - traefik.http.services.backend_eu.loadbalancer.server.port=5000      
    networks:
      - lang-network      

networks:
  lang-network:
    external: true 