services:
  traefik:
    image: traefik:v3.3
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
 
  frontend:
    build:
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.services.frontend.loadbalancer.server.port=80
 
  backend:
    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/api/dict`)
      - traefik.http.services.backend.loadbalancer.server.port=5000
 