version: "2"
services:
  frontend_en:
    build:
      context: ./frontend    
    ports:
      - "8082:80"
    networks:
      - my-net
  backend_en:
    build:
      context: ./backend    
    ports:
      - "5002:5002"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge 
    name: my-net
    external: true