version: "2"
services:
  frontend_de:
    build:
      context: ./frontend    
    ports:
      - "8085:80"
    networks:
      - my-net-de  
  backend_de:
    build:
      context: ./backend    
    ports:
      - "5005:5000"
    networks:
      - my-net-de

networks:
  my-net-de:
