version: "2"
services:
  frontend_south_africa:
    build:
      context: ./frontend
    ports:
      - "8084:80"
    networks:
      - my-net
  backend_south_africa:
    build:
      context: ./backend   
    ports:
      - "5004:5004"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
    name: my-net
    external: true  
