services:
  frontend_af:
    build:
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend_eu.rule=PathPrefix(`/wordnet-eu`)
      - traefik.http.services.frontend_eu.loadbalancer.server.port=80
 
  backend_af:
    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_eu.rule=PathPrefix(`/api/dict`) && Headers(`X-Lang`, `eu`)
      - traefik.http.services.backend_eu.loadbalancer.server.port=5000      
 