version: "2"
services:
  frontend_en:
    build:
      context: ./frontend    
    ports:
      - "8082:80"
    networks:
      - my-net-en  
  backend_en:
    build:
      context: ./backend    
    ports:
      - "5002:5000"
    networks:
      - my-net-en

networks:
  my-net-en:
