services:
  frontend_af:
    build:
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend_de.rule=PathPrefix(`/wordnet-de`)
      - traefik.http.services.frontend_de.loadbalancer.server.port=80
 
  backend_af:
    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_de.rule=PathPrefix(`/api/dict`) && Headers(`X-Lang`, `de`)
      - traefik.http.services.backend_de.loadbalancer.server.port=5000      
 