services:
  frontend_af:
    build:
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend_south_africa.rule=PathPrefix(`/wordnet-south-africa`)
      - traefik.http.services.frontend_south_africa.loadbalancer.server.port=80
 
  backend_af:
    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_south_africa.rule=PathPrefix(`/api/dict`) && Headers(`X-Lang`, `south-africa`)
      - traefik.http.services.backend_south_africa.loadbalancer.server.port=5000      
 