version: "2"
services:
  frontend_south_africa:
    build:
      context: ./frontend    
    ports:
      - "8084:80"
    networks:
      - my-net-south-africa  
  backend_south_africa:
    build:
      context: ./backend    
    ports:
      - "5004:5000"
    networks:
      - my-net-south-africa

networks:
  my-net-south-africa:
