version: "2"
services:
  frontend_ua:
    build:
      context: ./frontend    
    ports:
      - "8086:80"
    networks:
      - my-net-ua  
  backend_ua:
    build:
      context: ./backend    
    ports:
      - "5006:5000"
    networks:
      - my-net-ua

networks:
  my-net-ua:
