version: "2"
services:
  frontend_de:
    build:
      context: ./frontend
    ports:
      - "8085:80"
    networks:
      - my-net
  backend_de:
    build:
      context: ./backend
    ports:
      - "5005:5005"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
    name: my-net
    external: true   