version: "2"
services:
  frontend_eu:
    build:
      context: ./frontend      
    ports:
      - "8081:80"
    networks:
      - my-net-eu  
  backend_eu:
    build:
      context: ./backend    
    ports:
      - "5001:5000"
    networks:
      - my-net-eu

networks:
  my-net-eu:
