version: "2"
services:
  frontend_eu:
    build:
      context: ./frontend
    ports:
      - "8081:80"
    networks:
      - my-net
  backend_eu:
    build:
      context: ./backend
    ports:
      - "5001:5001"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
    name: my-net
    external: true