version: "2"
services:
  frontend_af:
    build:
      context: ./frontend    
    ports:
      - "8083:8083"
    networks:
      - my-net  
  backend_af:
    build:
      context: ./backend    
    ports:
      - "5003:5003"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge 
    name: my-net
    external: true    