services:
  frontend_south_africa:
    build:
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend_south_africa.rule=PathPrefix(`/wordnet-south-africa`)
      - traefik.http.routers.frontend_south_africa.middlewares=frontend_south_africa-stripprefix
      - traefik.http.services.frontend_south_africa.loadbalancer.server.port=80
      - traefik.http.middlewares.frontend_south_africa-stripprefix.stripprefix.prefixes=/wordnet-south-africa
    networks:
      - lang-network      
 
  backend_south_africa:
    build:
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend_south_africa.rule=PathPrefix(`/api/dict`) && Header(`X-Lang`, `south-africa`)
      - traefik.http.services.backend_south_africa.loadbalancer.server.port=5000      
    networks:
      - lang-network      

networks:
  lang-network:
    external: true 