version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my-net-af
      - my-net-de
      - my-net-en
      - my-net-eu
      - my-net-south-africa
      - my-net-ua                        

networks:
  my-net-af:
  my-net-de:
  my-net-en:
  my-net-eu:
  my-net-south-africa:
  my-net-ua:        
